# Add this step instead of the complex backup system
- name: Simple periodic backup
  run: |
    $endTime = (Get-Date).AddMinutes(355)
    $lastBackup = Get-Date
    
    while ((Get-Date) -lt $endTime) {
        # Backup every 5 minutes
        if ((Get-Date) - $lastBackup -gt (New-TimeSpan -Minutes 5)) {
            Write-Host "Backing up files..."
            Copy-Item -Path "C:\Users\RDP4\Documents\*" -Destination "./persistent-storage/Documents\" -Recurse -Force -ErrorAction SilentlyContinue
            Copy-Item -Path "C:\Users\RDP4\Desktop\*" -Destination "./persistent-storage/Desktop\" -Recurse -Force -ErrorAction SilentlyContinue
            Copy-Item -Path "C:\Users\RDP4\Downloads\*" -Destination "./persistent-storage/Downloads\" -Recurse -Force -ErrorAction SilentlyContinue
            
            git add ./persistent-storage/
            git commit -m "Backup: $(Get-Date -Format 'HH:mm')" || echo "No changes"
            git push origin main
            
            $lastBackup = Get-Date
        }
        
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] RDP Active"
        Start-Sleep -Seconds 30
    }
